version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      - LLM_HOST=${LLM_HOST}
      - LLM_PORT=${LLM_PORT}
      - OCR_URL=${OCR_URL}
      - VECTOR_DB_HOST=${VECTOR_DB_HOST}
      - VECTOR_DB_PORT=${VECTOR_DB_PORT}
    depends_on:
      - llm
      - ocr
      - vectordb

  llm:
    build:
      context: ./LLM
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=LLM
      - OLLAMA_PORT=11434
    volumes:
      - ollama-data:/root/.ollama

  ocr:
    build:
      context: ./OCR
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT} 

  vectordb:
    image: chromadb/chroma
    ports:
      - 8000:8000
    environment:
      - VECTOR_DB_PORT=${VECTOR_DB_PORT}

volumes:
  ollama-data: